services:
     mysql:
          image: mysql:8.0
          container_name: cydb
          environment:
               MYSQL_DATABASE: ${MYSQL_DATABASE}
               MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
               MYSQL_PASSWORD: ${MYSQL_PASSWORD}
               MYSQL_USER: ${MYSQL_USER}
          ports:
               - "3308:3306"
          volumes:
               - ./mysql_data:/var/lib/mysql
               - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
