services:
     mysql:
          image: postgres:17
          container_name: cy-solicitudes
          environment:
               POSTGRES_DB: ${POSTGRES_DB}
               POSTGRES_USER: ${POSTGRES_USER}
               POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          ports:
               - "5433:5432"
          volumes:
               - ./postgres_data:/var/lib/postgresql/data
               - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
